// Code generated by "stringer -type State -linecomment raft.go"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Down-0]
	_ = x[Follower-1]
	_ = x[Candidate-2]
	_ = x[Leader-3]
}

const _State_name = "downfollowercandidateleader"

var _State_index = [...]uint8{0, 4, 12, 21, 27}

func (i State) String() string {
	if i < 0 || i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
